apiVersion: v1
kind: Secret
metadata:
  name: mi-demo-secrets
type: Opaque
stringData:
  APP_ENV: prod
  DATABASE_URL: replace-me
  SUPABASE_URL: replace-me
  SUPABASE_SERVICE_ROLE_KEY: replace-me
  SUPABASE_STORAGE_BUCKET: mi-demo-assets
